/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Business.IEmployee;
import java.util.List;
import java.util.ArrayList;
import Business.IEmployee;
import Business.EmployeeFactory;
import Business.Student;
import Business.Teacher;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author apple
 */

public class EmployeeJFrame extends javax.swing.JFrame {

    /**
     * Creates new form EmployeeJFrame
     */
    ArrayList<IEmployee> employees;
    public EmployeeJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblList = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtTodayDate = new javax.swing.JTextField();
        txtPayrollTotal = new javax.swing.JTextField();
        txtEmployeeTotal = new javax.swing.JTextField();
        btnShow = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Employee ID", "Date", "Name (Employee Type)", "Pay Category", "Salary", "Hours", "Bonus", "Gross Pay"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblList);

        jLabel7.setText("Date");

        jLabel8.setText("Payroll Total");

        jLabel9.setText("Employee Total");

        txtTodayDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTodayDateActionPerformed(evt);
            }
        });

        btnShow.setText("Show");
        btnShow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowActionPerformed(evt);
            }
        });

        jButton4.setText("Exit");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTodayDate, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(75, 75, 75)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPayrollTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(71, 71, 71)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtEmployeeTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnShow))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(txtTodayDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPayrollTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEmployeeTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnShow)
                    .addComponent(jButton4))
                .addContainerGap())
        );

        txtTodayDate.getAccessibleContext().setAccessibleName("txtDate");
        txtPayrollTotal.getAccessibleContext().setAccessibleName("txtPayrollTable");
        txtEmployeeTotal.getAccessibleContext().setAccessibleName("txtEmployeeTotal");
        btnShow.getAccessibleContext().setAccessibleName("txtShow");
        jButton4.getAccessibleContext().setAccessibleName("btnExit");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtTodayDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTodayDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTodayDateActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void btnShowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowActionPerformed
        // TODO add your handling code here:
        try{
        int ID= tblList.getSelectedRow();
        MainJFrame MainForm=new MainJFrame();
        MainForm.txtFullName.setText(String.valueOf(employees.get(ID).getFirstName())+" "+
                                            String.valueOf(employees.get(ID).getLastName()));
        MainForm.txtEmployeeID.setText(String.valueOf(employees.get(ID).getEmployeeID()));
        MainJFrame.txtPhoneNumber.setText(String.valueOf(employees.get(ID).getPhone()));
        MainJFrame.txtAddress.setText(String.valueOf(employees.get(ID).getAddress()));
        MainJFrame.txtEmployeeType.setText(employees.get(ID).getPayCategory());
        MainJFrame.txtHours.setText(String.valueOf(employees.get(ID).getHours()));
        MainJFrame.txtPayCategory.setText(String.valueOf(employees.get(ID).getPayCategory()));
        MainJFrame.txtSalary.setText(String.valueOf(employees.get(ID).getSalaryWage()));
        MainJFrame.txtBonuses.setText(String.valueOf(employees.get(ID).getBonus()));
        MainForm.txtTotal.setText(String.valueOf(employees.get(ID).getTotal()));
        MainForm.setVisible(true);
        this.hide();
        
                }
        catch(Exception e)
        {
            
        }
    }//GEN-LAST:event_btnShowActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmployeeJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmployeeJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmployeeJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmployeeJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmployeeJFrame().setVisible(true);
            }
        });
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnShow;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblList;
    private javax.swing.JTextField txtEmployeeTotal;
    private javax.swing.JTextField txtPayrollTotal;
    private javax.swing.JTextField txtTodayDate;
    // End of variables declaration//GEN-END:variables

public   void loadListingTable() {
        // TODO: Add the columns for other attributes
        DefaultTableModel defaultTableModel = (DefaultTableModel)tblList.getModel();
        defaultTableModel.setRowCount(0);
       double TotalPayroll=0;
        for(IEmployee employee : employees)
        {
            
            if(employee.getPayments().size()!=0)
            {
            Object[] row = new Object[8];
            row[0] = employee.getEmployeeID();
            row[1] = employee.getPayDate();
            row[2]= employee.getFirstName()+" "+employee.getLastName();
            row[3]=employee.getPayCategory();
            row[4]=employee.getSalaryWage();
            row[5]=employee.getHours();
            row[6]=employee.getBonus();
            row[7]=employee.getTotal();
            TotalPayroll+=employee.getTotal();
            defaultTableModel.addRow(row);
            }
        
        }
    Date dt=new Date();
    SimpleDateFormat sdf = new SimpleDateFormat("yyyy/MM/dd HH:mm");
System.out.println(sdf.format(dt));
    txtTodayDate.setText(dt.toString());
    txtEmployeeTotal.setText(String.valueOf(tblList.getRowCount()));
    
    txtPayrollTotal.setText(String.valueOf(TotalPayroll) );
        
    }


}
